In [2]:
import random
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_scatter import scatter_mean, scatter_softmax, scatter_sum

In [39]:
a = torch.ones(5,3,4)
b = torch.ones(5,4,3)
b = torch.unsqueeze(b, dim=1)
z1 = F.normalize(a)
z2 = F.normalize(b)
print(z1.shape)
print(z2.shape)

torch.Size([5, 3, 4])
torch.Size([5, 1, 4, 3])


torch.Size([5, 3, 4])
torch.Size([5, 4, 3])


In [40]:
print(torch.matmul(z1,z2).shape)

torch.Size([5, 5, 3, 3])


In [19]:
f = lambda x: torch.exp(x / 0.6)

In [20]:
refl_sim = f(torch.mm(z1,z1.t()))
print(refl_sim)

tensor([[5.2945]])


In [37]:
a = torch.ones(5,3,4)
b = torch.ones(5,3,4)
print(a+b)

tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])


In [42]:
a = torch.ones(5,3,4)

In [54]:
print(torch.log(a/a).shape)

torch.Size([5, 3, 4])


In [56]:
print (torch.cuda.is_available())

True


In [1]:
print("a:", a)

NameError: name 'a' is not defined

In [60]:
for line in open("../data/movie/ratings.dat", encoding='utf-8').readlines()[1:]:
    print(line)
    array = line.strip().split(",")
    print(array)

FileNotFoundError: [Errno 2] No such file or directory: '../data/movie/ratings.dat'

In [3]:
initializer = nn.init.xavier_uniform_

In [5]:
print(initializer(torch.empty(5,3,4)))

tensor([[[ 0.0023, -0.0916, -0.0376, -0.1607],
         [ 0.3532,  0.0865, -0.0343, -0.3435],
         [-0.2729, -0.2534, -0.3767, -0.3577]],

        [[ 0.1248, -0.2526,  0.0500, -0.2600],
         [-0.2145,  0.1379,  0.2771, -0.1741],
         [-0.2657,  0.0006, -0.0975,  0.0027]],

        [[ 0.1008, -0.2623, -0.0295,  0.3136],
         [-0.3442,  0.3133, -0.0192, -0.4099],
         [ 0.3772, -0.0859,  0.3889,  0.4078]],

        [[ 0.3035,  0.0717, -0.3576,  0.1124],
         [-0.0725, -0.0979, -0.2002, -0.0809],
         [ 0.1506, -0.1529,  0.0087, -0.0451]],

        [[-0.0710, -0.2904,  0.1832, -0.1195],
         [-0.0542, -0.1976, -0.3441,  0.4152],
         [-0.2683,  0.1827,  0.2582, -0.1587]]])


In [6]:
print(nn.Parameter(initializer(torch.empty(5,3,4))))

Parameter containing:
tensor([[[ 0.2718,  0.4289,  0.1844, -0.1984],
         [-0.1363, -0.3108, -0.3838, -0.2457],
         [-0.2824, -0.1824,  0.1278,  0.0764]],

        [[-0.2062, -0.4054, -0.2484, -0.4105],
         [-0.0276,  0.4328,  0.0484, -0.4254],
         [-0.1554, -0.2881,  0.3772, -0.3234]],

        [[-0.2096, -0.1767, -0.4111, -0.2513],
         [ 0.0479, -0.1873,  0.2196,  0.1513],
         [-0.2463,  0.0417,  0.1265, -0.2525]],

        [[ 0.0547, -0.1507,  0.0158, -0.3707],
         [ 0.0901,  0.0712, -0.0006, -0.1754],
         [-0.2636, -0.0197,  0.2185, -0.2409]],

        [[-0.2022,  0.3391,  0.1256,  0.3797],
         [ 0.2070, -0.0863,  0.4050,  0.1093],
         [-0.2905,  0.2899,  0.2760,  0.3301]]], requires_grad=True)


In [8]:
x = torch.Tensor([[[-7.0105e-04, -3.2230e-03, -3.0518e-03, 2.1315e-03,3.1769e-03, -3.1840e-03]]])
x
                  

tensor([[-0.0007, -0.0032, -0.0031,  0.0021,  0.0032, -0.0032]])

In [10]:
print(x * x.t())

tensor([[ 4.9147e-07,  2.2595e-06,  2.1395e-06, -1.4943e-06, -2.2272e-06,
          2.2321e-06],
        [ 2.2595e-06,  1.0388e-05,  9.8360e-06, -6.8698e-06, -1.0239e-05,
          1.0262e-05],
        [ 2.1395e-06,  9.8360e-06,  9.3135e-06, -6.5049e-06, -9.6953e-06,
          9.7169e-06],
        [-1.4943e-06, -6.8698e-06, -6.5049e-06,  4.5433e-06,  6.7716e-06,
         -6.7867e-06],
        [-2.2272e-06, -1.0239e-05, -9.6953e-06,  6.7716e-06,  1.0093e-05,
         -1.0115e-05],
        [ 2.2321e-06,  1.0262e-05,  9.7169e-06, -6.7867e-06, -1.0115e-05,
          1.0138e-05]])


In [26]:
e_u = torch.Tensor([[[ 1.1289e-03, -3.8063e-03, -2.0272e-03,  1.8959e-03,  1.1147e-03,
          -2.1979e-03,  1.6707e-04, -1.4767e-03, -3.1361e-04,  1.8171e-04,
           2.5186e-04, -5.5382e-04, -1.5639e-03, -1.8387e-03,  4.3584e-04,
          -8.9234e-04, -1.1532e-03, -6.1461e-04,  2.0511e-03, -4.5909e-04,
           1.1041e-03,  2.0469e-03,  1.8909e-03, -8.1280e-04,  2.2497e-03,
           2.0253e-03,  1.7243e-04, -5.1806e-04, -2.6200e-03,  2.0247e-03,
           1.7220e-04,  9.8080e-04,  1.6467e-03, -9.3666e-04, -1.3103e-03,
          -2.2962e-03, -1.4705e-06, -2.6853e-04, -2.4626e-03,  5.4153e-04,
          -1.3133e-03, -6.0677e-04,  1.8496e-05,  1.2624e-03, -9.8180e-04,
          -2.3294e-03,  1.5032e-03,  6.7908e-04, -9.2482e-04, -1.0517e-03,
           7.0310e-04,  7.8743e-04, -3.0965e-03, -8.3023e-04,  1.1589e-03,
          -6.1037e-04,  1.5627e-03, -1.0320e-03,  5.8567e-04, -1.4341e-03,
          -6.9118e-04,  2.6382e-03, -5.9178e-04,  3.2775e-04],
         [ 1.9329e-03, -1.3387e-03, -2.3865e-03, -8.6180e-04, -2.4911e-03,
          -3.2739e-04, -1.7550e-03,  6.7474e-04,  5.4897e-04,  2.0699e-03,
           6.0544e-04, -8.3193e-04,  3.1310e-04,  1.1663e-03,  3.2150e-04,
          -1.5184e-03, -3.5886e-04,  9.3525e-04, -3.1758e-03, -1.6784e-03,
          -1.5301e-03,  2.5443e-04,  5.9403e-05,  3.0328e-04,  2.6342e-04,
           4.0601e-04,  1.6908e-03,  2.2904e-03, -1.2549e-04, -7.2190e-04,
          -2.2669e-03,  1.6126e-03,  5.9665e-04, -2.4414e-04, -2.0321e-03,
           2.2138e-03, -3.3728e-03,  5.9939e-04, -2.9088e-05,  1.0290e-03,
           1.0265e-05, -1.3706e-03,  1.3657e-03, -5.3590e-04, -9.1353e-04,
           2.1910e-03, -1.5970e-04, -4.6321e-04, -1.7264e-03, -3.8410e-04,
          -1.3535e-03, -2.8186e-03, -2.9161e-03, -3.3701e-03,  1.9064e-03,
          -1.1415e-05,  7.2578e-04,  1.4151e-03, -4.8636e-04, -1.7220e-03,
           2.7505e-04,  2.1286e-03,  3.2610e-03, -1.3800e-03]],

        [[-1.4838e-03, -2.1756e-03, -8.2324e-04,  7.7396e-04,  5.6800e-04,
           3.3372e-05, -6.2312e-04, -2.6387e-04,  1.5313e-03,  5.2807e-04,
           2.4404e-04, -4.3855e-04,  2.0983e-04, -3.0107e-04, -1.2589e-03,
          -6.8535e-04, -1.5299e-03, -5.1862e-04, -4.4012e-04,  3.6296e-04,
          -1.7566e-03,  9.8982e-04, -1.4944e-04,  6.0881e-04, -2.0675e-03,
          -6.4805e-04,  1.6142e-03, -1.2701e-04, -1.3096e-03, -1.7242e-03,
          -4.4371e-04,  1.5248e-03,  9.6535e-04,  2.7656e-04, -4.5443e-05,
          -1.0405e-03,  1.4808e-04, -7.6610e-04,  2.4121e-04,  1.9256e-04,
          -1.0490e-03, -4.0455e-04,  2.8097e-04,  1.1190e-03,  1.6304e-03,
           7.6030e-04,  4.2948e-04,  5.7714e-04, -8.4248e-04, -2.4484e-04,
          -8.7697e-04,  1.3251e-04, -6.3986e-04, -1.9481e-03, -1.2595e-03,
          -1.0504e-03, -1.8919e-03,  1.4168e-03, -5.2094e-04, -2.5072e-03,
          -7.5607e-05,  6.8087e-04,  4.6684e-04,  5.4622e-04],
         [ 2.3646e-03, -3.2648e-03, -2.4115e-03, -1.0884e-04,  6.7420e-04,
           3.3135e-06,  5.0832e-04,  2.3465e-03, -1.5673e-03,  5.9209e-05,
           1.4212e-03, -9.9604e-04,  2.9877e-03, -4.7086e-04, -2.7339e-03,
          -5.4923e-04, -1.9302e-04, -2.7802e-04, -8.4884e-04, -4.4285e-04,
          -8.5721e-04,  1.9266e-03, -1.0968e-03,  6.4049e-04, -5.4745e-04,
           3.8313e-04,  9.5557e-04,  7.7170e-04, -8.0653e-04,  6.5857e-04,
          -7.2077e-04,  7.9551e-04, -9.4580e-05,  1.5035e-03,  2.6033e-04,
          -7.3069e-04,  7.6940e-04, -4.1508e-04,  4.6009e-04,  4.1720e-04,
          -3.0541e-03, -9.1449e-04,  3.7627e-04,  7.4015e-04, -3.2742e-05,
          -1.0049e-03,  8.5935e-04, -4.6822e-04,  5.6887e-04,  4.2427e-04,
           1.1394e-03, -1.1925e-03,  2.3216e-04, -9.5663e-04,  1.6597e-04,
          -1.0927e-05, -4.6482e-05, -1.3238e-03,  1.3414e-03, -1.4994e-03,
          -1.1870e-03,  2.2174e-03, -4.9092e-04, -1.8111e-05]]])
print(e_u)

tensor([[[ 1.1289e-03, -3.8063e-03, -2.0272e-03,  1.8959e-03,  1.1147e-03,
          -2.1979e-03,  1.6707e-04, -1.4767e-03, -3.1361e-04,  1.8171e-04,
           2.5186e-04, -5.5382e-04, -1.5639e-03, -1.8387e-03,  4.3584e-04,
          -8.9234e-04, -1.1532e-03, -6.1461e-04,  2.0511e-03, -4.5909e-04,
           1.1041e-03,  2.0469e-03,  1.8909e-03, -8.1280e-04,  2.2497e-03,
           2.0253e-03,  1.7243e-04, -5.1806e-04, -2.6200e-03,  2.0247e-03,
           1.7220e-04,  9.8080e-04,  1.6467e-03, -9.3666e-04, -1.3103e-03,
          -2.2962e-03, -1.4705e-06, -2.6853e-04, -2.4626e-03,  5.4153e-04,
          -1.3133e-03, -6.0677e-04,  1.8496e-05,  1.2624e-03, -9.8180e-04,
          -2.3294e-03,  1.5032e-03,  6.7908e-04, -9.2482e-04, -1.0517e-03,
           7.0310e-04,  7.8743e-04, -3.0965e-03, -8.3023e-04,  1.1589e-03,
          -6.1037e-04,  1.5627e-03, -1.0320e-03,  5.8567e-04, -1.4341e-03,
          -6.9118e-04,  2.6382e-03, -5.9178e-04,  3.2775e-04],
         [ 1.9329e-03, -1.3387e-03, -

In [27]:
e_u = F.normalize(e_u, dim=2)
print("e_u:",e_u)
print("e_u.shape:",e_u.shape)

e_u: tensor([[[ 9.7187e-02, -3.2768e-01, -1.7452e-01,  1.6322e-01,  9.5964e-02,
          -1.8922e-01,  1.4383e-02, -1.2713e-01, -2.6999e-02,  1.5643e-02,
           2.1683e-02, -4.7678e-02, -1.3464e-01, -1.5829e-01,  3.7521e-02,
          -7.6821e-02, -9.9279e-02, -5.2912e-02,  1.7658e-01, -3.9523e-02,
           9.5052e-02,  1.7622e-01,  1.6279e-01, -6.9974e-02,  1.9368e-01,
           1.7436e-01,  1.4844e-02, -4.4600e-02, -2.2556e-01,  1.7431e-01,
           1.4825e-02,  8.4437e-02,  1.4176e-01, -8.0637e-02, -1.1280e-01,
          -1.9768e-01, -1.2660e-04, -2.3118e-02, -2.1200e-01,  4.6620e-02,
          -1.1306e-01, -5.2237e-02,  1.5923e-03,  1.0868e-01, -8.4523e-02,
          -2.0054e-01,  1.2941e-01,  5.8462e-02, -7.9618e-02, -9.0541e-02,
           6.0530e-02,  6.7790e-02, -2.6658e-01, -7.1474e-02,  9.9769e-02,
          -5.2547e-02,  1.3453e-01, -8.8845e-02,  5.0420e-02, -1.2346e-01,
          -5.9504e-02,  2.2712e-01, -5.0946e-02,  2.8216e-02],
         [ 1.5487e-01, -1.0726e-

In [28]:
e_u_T = torch.transpose(e_u, 1, 2)
print("e_u_T.shape:",e_u_T.shape)

e_u_T.shape: torch.Size([2, 64, 2])


In [36]:
f = lambda x: torch.exp(x / 0.6)
pos_sample = f(torch.matmul(e_u, e_u_T))
print("pos_sample_u:", pos_sample)
print("pos_sample_u.shape:", pos_sample.shape)

pos_sample_u: tensor([[[5.2945, 1.1562],
         [1.1562, 5.2945]],

        [[5.2945, 1.6594],
         [1.6594, 5.2945]]])
pos_sample_u.shape: torch.Size([2, 2, 2])


In [37]:
print(pos_sample.sum(2)- torch.diagonal(pos_sample, 0, dim1=-2, dim2=-1))

tensor([[1.1562, 1.1562],
        [1.6594, 1.6594]])


In [51]:
pos_sample = pos_sample.sum(2) - torch.diagonal(pos_sample, 0, dim1=-2, dim2=-1)
#B, 1, D, K
e_u_T_t = torch.unsqueeze(e_u_T, dim=1)
print(e_u_T_t.shape)
#B, B, K, K
all_sample = f(torch.matmul(e_u, e_u_T_t))
print(all_sample)
#B, B, K
all_sample_u = all_sample.sum(3)-torch.diagonal(all_sample, 0, dim1=-2, dim2=-1)
print("all_sample_u:", all_sample_u)
#B, K
all_sample_uu = all_sample_u.sum(1)
print("all_sample_uu", all_sample_uu)

torch.Size([2, 1, 64, 2])
tensor([[[[5.2945, 1.1562],
          [1.1562, 5.2945]],

         [[1.3012, 1.5704],
          [1.6696, 1.4432]]],


        [[[1.3012, 1.6696],
          [1.5704, 1.4432]],

         [[5.2945, 1.6594],
          [1.6594, 5.2945]]]])
all_sample_u: tensor([[[1.1562, 1.1562],
         [1.5704, 1.6696]],

        [[1.6696, 1.5704],
         [1.6594, 1.6594]]])
all_sample_uu tensor([[2.7266, 2.8259],
        [3.3290, 3.2297]])


In [52]:
loss_u = - torch.log(pos_sample / all_sample_uu)
print("loss_u:", loss_u)
print(loss_u.shape)

loss_u: tensor([[0.8579, 0.8936],
        [0.6962, 0.6660]])
torch.Size([2, 2])


In [57]:
crossloss = loss_u
crossloss = crossloss.mean()
crossloss = crossloss.sum()


print(crossloss)

tensor(0.7784)


In [62]:
na = [np.nan, 1, 2]

In [63]:
na

[nan, 1, 2]

In [65]:
print(np.nan in na)

True


In [87]:
dataset = "article"

# kg_np = np.load('/data/ftp_files/chenqh/2021/DHAN/data/'+dataset+'/kg_final.npy')
kg_np = np.load('../data/'+dataset+'/kg_final.npy')
n_entity = max(max(kg_np[:, 0]), max(kg_np[:, 2])) + 1
n_relation = max(kg_np[:, 1]) + 1


rating_np = np.load('../data/'+dataset+'/ratings_final.npy')
n_user = max(rating_np[:, 0]) + 1
n_node = n_user + n_entity
n_item = max(rating_np[:, 1]) + 1
# # remap user id
# rating_np[:, 0] = rating_np[:, 0] + n_entity
# users = set(rating_np[:, 0])
# items = set(rating_np[:, 1])

print('n_user:               %d' % n_user)
print('n_item:               %d' % n_item)
print('n_node:               %d' % n_node)
print('n_entity:             %d' % n_entity)
print('n_relation:           %d' % n_relation)
print('n_ratings:            %d' % rating_np.shape[0])
print('n_triples:            %d' % kg_np.shape[0])

n_user:               5547
n_item:               11714
n_node:               17261
n_entity:             11714
n_relation:           1
n_ratings:            295146
n_triples:            89418
